=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/Ejercicio1-2.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/ejercicio1-2" xmlns="http://www.example.org/ejercicio1-2"
	elementFormDefault="qualified">

	<xs:complexType name="tipo_emision">
		<xs:attribute name="titulo" type="xs:string" />
		<xs:attribute name="fecha" type="xs:date" />
		<xs:attribute name="tiempo" type="xs:time" />
		<xs:attribute name="URL" type="xs:string" />
	</xs:complexType>

	<xs:element name="programa">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nombre" type="xs:string" />
				<xs:element name="URLprograma" type="xs:string" />
				<xs:element name="URLimagen" type="xs:string" />
				<xs:element name="emision" type="tipo_emision" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/aguila-roja.xml
<?xml version="1.0" ?>
<p:programa xmlns:p="http://www.example.org/ejercicio1-2"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/ejercicio1-2 Ejercicio1-2.xsd "
	id="aguila-roja">
	<p:nombre>Águila Roja</p:nombre>
	<p:URLprograma>http://www.rtve.es/m/alacarta/videos/el-siglo-de-aguila-roja/?media=tve</p:URLprograma>
	<p:URLimagen>http://img.rtve.es/imagenes/aguila-roja/1412769760573.png</p:URLimagen>
	<p:emision titulo="T9 - Capítulo 116" fecha="2016-10-27"
		tiempo="01:27:40"
		URL="http://www.rtve.es/m/alacarta/videos/aguila-roja/aguila-roja-t9-capitulo-116/3771566/?media=tve"></p:emision>
	<p:emision titulo="T9 - Capítulo 115" fecha="2016-10-20"
		tiempo="01:21:25"
		URL="http://www.rtve.es/m/alacarta/videos/aguila-roja/aguila-roja-t9-capitulo-115/3763280/?media=tve"></p:emision>
	<p:emision titulo="T9 - Capítulo 114" fecha="2016-10-13"
		tiempo="01:16:39"
		URL="http://www.rtve.es/m/alacarta/videos/aguila-roja/aguila-roja-t9-capitulo-114/3752919/?media=tve"></p:emision>
	<p:emision titulo="T9 - Capítulo 113" fecha="2016-10-06"
		tiempo="01:18:45"
		URL="http://www.rtve.es/m/alacarta/videos/aguila-roja/aguila-roja-t9-capitulo-113/3745187/?media=tve"></p:emision>
	<p:emision titulo="T9 - Capítulo 112" fecha="2016-09-29"
		tiempo="01:18:43"
		URL="http://www.rtve.es/m/alacarta/videos/aguila-roja/aguila-roja-t9-capitulo-112/3736718/?media=tve"></p:emision>
	<p:emision titulo="T9 - Capítulo 111" fecha="2016-09-22"
		tiempo="01:19:10"
		URL="http://www.rtve.es/m/alacarta/videos/aguila-roja/aguila-roja-t9-capitulo-111/3728076/?media=tve"></p:emision>
	<p:emision titulo="T9 - Capítulo 110" fecha="2016-09-15"
		tiempo="01:18:11"
		URL="http://www.rtve.es/m/alacarta/videos/aguila-roja/aguila-roja-t9-capitulo-110/3719743/?media=tve"></p:emision>
	<p:emision titulo="T9 - Capítulo 109" fecha="2016-07-19"
		tiempo="01:19:07"
		URL="http://www.rtve.es/m/alacarta/videos/aguila-roja/aguila-roja-t9-capitulo-109/3664155/?media=tve"></p:emision>
	<p:producto ASIN="B01M3SFI3A" Titulo="Águila Roja Serie Completa DVD"
		urlImgSmall="https://images-eu.ssl-images-amazon.com/images/I/51C4HToxVXL._SL75_.jpg"
		urlImgLarge="https://images-eu.ssl-images-amazon.com/images/I/51C4HToxVXL.jpg"
		Precio="EUR 127,00"
		URL="https://www.amazon.es/%C3%81guila-Roja-Serie-Completa-DVD/dp/B01M3SFI3A?SubscriptionId=AKIAJAYMJWKJ3W7LP7UQ&amp;tag=arso&amp;linkCode=xm2&amp;camp=2025&amp;creative=165953&amp;creativeASIN=B01M3SFI3A"></p:producto>
	<p:producto ASIN="B01MFA8ZRR" Titulo="Águila Roja Temporada 9 DVD"
		urlImgSmall="https://images-eu.ssl-images-amazon.com/images/I/51KZ2jXorwL._SL75_.jpg"
		urlImgLarge="https://images-eu.ssl-images-amazon.com/images/I/51KZ2jXorwL.jpg"
		Precio="EUR 28,92"
		URL="https://www.amazon.es/%C3%81guila-Roja-Temporada-9-DVD/dp/B01MFA8ZRR?SubscriptionId=AKIAJAYMJWKJ3W7LP7UQ&amp;tag=arso&amp;linkCode=xm2&amp;camp=2025&amp;creative=165953&amp;creativeASIN=B01MFA8ZRR"></p:producto>
	<p:producto ASIN="B006ZVONAQ" Titulo="Aguila Roja DVD David Janer"
		urlImgSmall="https://images-eu.ssl-images-amazon.com/images/I/51d89cIVORL._SL75_.jpg"
		urlImgLarge="https://images-eu.ssl-images-amazon.com/images/I/51d89cIVORL.jpg"
		Precio="EUR 8,11"
		URL="https://www.amazon.es/Aguila-Roja-DVD-David-Janer/dp/B006ZVONAQ?SubscriptionId=AKIAJAYMJWKJ3W7LP7UQ&amp;tag=arso&amp;linkCode=xm2&amp;camp=2025&amp;creative=165953&amp;creativeASIN=B006ZVONAQ"></p:producto>
</p:programa>

=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/alaska-y-segura.xml
<?xml version="1.0" ?>
<p:programa xmlns:p="http://www.example.org/ejercicio1-2"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/ejercicio1-2 Ejercicio1-2.xsd "
	id="alaska-y-segura">
	<p:nombre>Alaska y Segura</p:nombre>
	<p:URLprograma>http://www.rtve.es/m/alacarta/videos/alaska-y-segura/?media=tve</p:URLprograma>
	<p:URLimagen>http://img.rtve.es/imagenes/alaska-segura/1423649639233.png</p:URLimagen>
	<p:emision titulo="Viva BuÃ±uel" fecha="2015-05-25" tiempo="00:1:41"
		URL="http://www.rtve.es/m/alacarta/videos/alaska-y-segura/alaska-segura-viva-bunuel/3141222/?media=tve"></p:emision>
	<p:emision titulo="Danzad malditos" fecha="2015-05-18"
		tiempo="00:1:22"
		URL="http://www.rtve.es/m/alacarta/videos/alaska-y-segura/alaska-segura-danzad-malditos/3132849/?media=tve"></p:emision>
	<p:emision titulo="La primera vez" fecha="2015-05-11" tiempo="00:1:41"
		URL="http://www.rtve.es/m/alacarta/videos/alaska-y-segura/alaska-segura-primera-vez/3124180/?media=tve"></p:emision>
	<p:emision titulo="La noche de los muertos vivientes" fecha="2015-05-04"
		tiempo="00:1:25"
		URL="http://www.rtve.es/m/alacarta/videos/alaska-y-segura/alaska-segura-noche-muertos-vivientes/3115898/?media=tve"></p:emision>
	<p:emision titulo="La bola de cristal" fecha="2015-04-20"
		tiempo="00:1:41"
		URL="http://www.rtve.es/m/alacarta/videos/alaska-y-segura/alaska-segura-bola-cristal/3099462/?media=tve"></p:emision>
	<p:emision titulo="La ley de la calle" fecha="2015-04-13"
		tiempo="00:1:18"
		URL="http://www.rtve.es/m/alacarta/videos/alaska-y-segura/alaska-segura-ley-calle/3089328/?media=tve"></p:emision>
	<p:emision titulo="Fan fatal" fecha="2015-04-06" tiempo="00:1:14"
		URL="http://www.rtve.es/m/alacarta/videos/alaska-y-segura/alaska-segura-fan-fatal/3077898/?media=tve"></p:emision>
	<p:emision titulo="Karaoke Kid" fecha="2015-03-30" tiempo="00:1:18"
		URL="http://www.rtve.es/m/alacarta/videos/alaska-y-segura/alaska-segura-karaoke-kid/3069819/?media=tve"></p:emision>
</p:programa>

=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/asi-se-hizo.xml
<?xml version="1.0" ?><p:programa xmlns:p="http://www.example.org/ejercicio1-2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ejercicio1-2 Ejercicio1-2.xsd " id="asi-se-hizo"><p:nombre>Así se hizo</p:nombre><p:URLprograma>http://www.rtve.es/m/alacarta/videos/asi-se-hizo/?media=tve</p:URLprograma><p:URLimagen>http://img.rtve.es/imagenes/asi-se-hizo/1298632031035.png</p:URLimagen><p:emision titulo="Invasor" fecha="2012-12-01" tiempo="00:12:04" URL="http://www.rtve.es/m/alacarta/videos/asi-se-hizo/asi-se-hizo-invasor/1597427/?media=tve"></p:emision><p:emision titulo="25 Kilates" fecha="2009-06-21" tiempo="00:14:54" URL="http://www.rtve.es/m/alacarta/videos/asi-se-hizo/asi-se-hizo-25-kilates/532296/?media=tve"></p:emision><p:emision titulo="NO-DO" fecha="2009-06-21" tiempo="00:22:20" URL="http://www.rtve.es/m/alacarta/videos/asi-se-hizo/asi-se-hizo-no-do/532301/?media=tve"></p:emision><p:emision titulo="Los mundos de Coraline" fecha="2009-06-15" tiempo="00:21:55" URL="http://www.rtve.es/m/alacarta/videos/asi-se-hizo/asi-se-hizo-mundos-coraline/532286/?media=tve"></p:emision><p:emision titulo="Antes de morir piensa " fecha="2009-06-13" tiempo="00:16:12" URL="http://www.rtve.es/m/alacarta/videos/asi-se-hizo/asi-se-hizo-antes-morir-piensa/543133/?media=tve"></p:emision><p:emision titulo="Coco, de la rebeldía a la leyenda" fecha="2009-06-13" tiempo="00:13:59" URL="http://www.rtve.es/m/alacarta/videos/asi-se-hizo/asi-se-hizo-coco-rebeldia-leyenda/532280/?media=tve"></p:emision><p:emision titulo="Fighting: Puños de asf" fecha="2009-06-13" tiempo="00:12:46" URL="http://www.rtve.es/m/alacarta/videos/asi-se-hizo/asi-se-hizo-fighting-punos-asfalto/532268/?media=tve"></p:emision><p:emision titulo="Terminator Salvation" fecha="2009-06-08" tiempo="00:23:51" URL="http://www.rtve.es/m/alacarta/videos/asi-se-hizo/asi-se-hizo-terminator-salvation/532304/?media=tve"></p:emision></p:programa>

=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/ana-y-los-siete.xml
<?xml version="1.0" ?>
<p:programa xmlns:p="http://www.example.org/ejercicio1-2"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/ejercicio1-2 Ejercicio1-2.xsd "
	id="ana-y-los-siete">
	<p:nombre>Ana y los siete</p:nombre>
	<p:URLprograma>http://www.rtve.es/m/alacarta/videos/ana-y-los-siete/?media=tve</p:URLprograma>
	<p:URLimagen>http://img.rtve.es/imagenes/ana-siete/1355752220204.jpg</p:URLimagen>
	<p:emision titulo="Episodio 91 - La esperada boda (II)"
		fecha="2013-09-01" tiempo="00:51:40"
		URL="http://www.rtve.es/m/alacarta/videos/ana-y-los-siete/ana-siete-episodio-91-esperada-boda-ii/1622902/?media=tve"></p:emision>
	<p:emision titulo="Episodio 90 - La esperada boda I" fecha="2012-12-21"
		tiempo="00:01:00"
		URL="http://www.rtve.es/m/alacarta/videos/ana-y-los-siete/ana-siete-episodio-90-esperada-boda/1621419/?media=tve"></p:emision>
	<p:emision titulo="Episodio 89 - ¿Y ahorá qué?" fecha="2012-12-20"
		tiempo="00:59:20"
		URL="http://www.rtve.es/m/alacarta/videos/ana-y-los-siete/ana-siente-episodio-89-ahora/1620062/?media=tve"></p:emision>
	<p:emision titulo="Episodio 88 - Un paso más" fecha="2012-12-19"
		tiempo="00:01:02"
		URL="http://www.rtve.es/m/alacarta/videos/ana-y-los-siete/ana-siete-episodio-88-paso-mas/1618806/?media=tve"></p:emision>
	<p:emision titulo="Episodio 87 - Maniobras" fecha="2012-12-18"
		tiempo="00:01:04"
		URL="http://www.rtve.es/m/alacarta/videos/ana-y-los-siete/ana-siete-episodio-87-maniobras/1617362/?media=tve"></p:emision>
	<p:emision titulo="Episodio 86 - Dudas de los Hidalgo" fecha="2012-12-18"
		tiempo="00:01:02"
		URL="http://www.rtve.es/m/alacarta/videos/ana-y-los-siete/ana-siete-episodio-86-dudas-hidalgo/1616188/?media=tve"></p:emision>
	<p:emision titulo="Episodio 85 - A veces oigo voces" fecha="2012-12-17"
		tiempo="00:56:34"
		URL="http://www.rtve.es/m/alacarta/videos/ana-y-los-siete/ana-siete-episodio-85-veces-oigo-voces/1612712/?media=tve"></p:emision>
	<p:emision titulo="Episodio 84 - De mal en peor" fecha="2012-12-14"
		tiempo="00:01:01"
		URL="http://www.rtve.es/m/alacarta/videos/ana-y-los-siete/ana-siete-episodio-84-mal-peor/1611229/?media=tve"></p:emision>
</p:programa>

=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/centro-medico.xml
<?xml version="1.0" ?><p:programa xmlns:p="http://www.example.org/ejercicio1-2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ejercicio1-2 Ejercicio1-2.xsd " id="centro-medico"><p:nombre>Centro médico</p:nombre><p:URLprograma>http://www.rtve.es/m/alacarta/videos/centro-medico/?media=tve</p:URLprograma><p:URLimagen>http://img.rtve.es/imagenes/centro-medico/1445510677793.png</p:URLimagen><p:emision titulo="Centro médico - 29/03/17 (2)     " fecha="2017-03-29" tiempo="00:33:53" URL="http://www.rtve.es/m/alacarta/videos/centro-medico/centro-medico-29-03-17-2/3961538/?media=tve"></p:emision><p:emision titulo="Centro médico - 29/03/17 (1)     " fecha="2017-03-29" tiempo="00:32:13" URL="http://www.rtve.es/m/alacarta/videos/centro-medico/centro-medico-29-03-17-1/3961474/?media=tve"></p:emision><p:emision titulo="Centro médico - 28/03/17 (2)    " fecha="2017-03-28" tiempo="00:34:04" URL="http://www.rtve.es/m/alacarta/videos/centro-medico/centro-medico-28-03-17-2/3960181/?media=tve"></p:emision><p:emision titulo="Centro médico - 28/03/17 (1)        " fecha="2017-03-28" tiempo="00:33:42" URL="http://www.rtve.es/m/alacarta/videos/centro-medico/centro-medico-28-03-17-1/3960164/?media=tve"></p:emision><p:emision titulo="Centro médico - 27/03/17 (2)   " fecha="2017-03-27" tiempo="00:34:19" URL="http://www.rtve.es/m/alacarta/videos/centro-medico/centro-medico-27-03-17-2/3959047/?media=tve"></p:emision><p:emision titulo="Centro médico - 27/03/17 (1)       " fecha="2017-03-27" tiempo="00:32:49" URL="http://www.rtve.es/m/alacarta/videos/centro-medico/centro-medico-27-03-17-1/3959041/?media=tve"></p:emision><p:emision titulo="Centro médico - 24/03/17 (2)" fecha="2017-03-24" tiempo="00:34:05" URL="http://www.rtve.es/m/alacarta/videos/centro-medico/centro-medico-500/3956173/?media=tve"></p:emision><p:emision titulo="Centro médico - 24/03/17 (1)" fecha="2017-03-24" tiempo="00:32:49" URL="http://www.rtve.es/m/alacarta/videos/centro-medico/centro-medico-24-03-17-1/3956187/?media=tve"></p:emision></p:programa>

=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/cantame-como-paso.xml
<?xml version="1.0" ?><p:programa xmlns:p="http://www.example.org/ejercicio1-2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ejercicio1-2 Ejercicio1-2.xsd " id="cantame-como-paso"><p:nombre>Cántame cómo pasó</p:nombre><p:URLprograma>http://www.rtve.es/m/alacarta/videos/cantame-como-paso/?media=tve</p:URLprograma><p:URLimagen>http://img.rtve.es/imagenes/cantame-como-paso/1296550456064.png</p:URLimagen><p:emision titulo="Final 2ª parte" fecha="2010-06-04" tiempo="00:36:16" URL="http://www.rtve.es/m/alacarta/videos/cantame-como-paso/cantame-como-paso-final-2-parte/791040/?media=tve"></p:emision><p:emision titulo="Final 1ª parte" fecha="2010-06-04" tiempo="00:1:54" URL="http://www.rtve.es/m/alacarta/videos/cantame-como-paso/cantame-como-paso-final-1-parte/791030/?media=tve"></p:emision><p:emision titulo="Programa 4" fecha="2010-05-28" tiempo="00:2:13" URL="http://www.rtve.es/m/alacarta/videos/cantame-como-paso/cantame-como-paso-28-05-2010/785402/?media=tve"></p:emision><p:emision titulo="Programa 3" fecha="2010-05-21" tiempo="00:1:59" URL="http://www.rtve.es/m/alacarta/videos/cantame-como-paso/cantame-como-paso-21-05-10/778975/?media=tve"></p:emision><p:emision titulo="Programa 2" fecha="2010-05-14" tiempo="00:2:07" URL="http://www.rtve.es/m/alacarta/videos/cantame-como-paso/cantame-como-paso-14-05-10/772255/?media=tve"></p:emision><p:emision titulo="Programa 1" fecha="2010-05-07" tiempo="00:2:02" URL="http://www.rtve.es/m/alacarta/videos/cantame-como-paso/cantame-como-paso-estreno-07-05-10/765501/?media=tve"></p:emision><p:emision titulo="Casting" fecha="2010-04-23" tiempo="00:1:01" URL="http://www.rtve.es/m/alacarta/videos/cantame-como-paso/especial-casting-cantame/753521/?media=tve"></p:emision><p:emision titulo="Filomena Fernández Zambrano" fecha="2010-02-15" tiempo="00:1:09" URL="http://www.rtve.es/m/alacarta/videos/cantame-como-paso/cantame-como-paso-filomena-fernandez-herminia/711749/?media=tve"></p:emision></p:programa>

=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/carlos-de-gante.xml
<?xml version="1.0" ?><p:programa xmlns:p="http://www.example.org/ejercicio1-2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ejercicio1-2 Ejercicio1-2.xsd " id="carlos-de-gante"><p:nombre>Carlos de Gante</p:nombre><p:URLprograma>http://www.rtve.es/m/alacarta/audios/carlos-de-gante/?media=tve</p:URLprograma><p:URLimagen>http://img.rtve.es/imagenes/carlos-gante/1441275607567.png</p:URLimagen><p:emision titulo="Carlos de Gante - Capítulo 5: &quot;El tablero de Europa&quot;" fecha="2015-09-30" tiempo="00:6:07" URL="http://www.rtve.es/m/alacarta/audios/carlos-de-gante/carlos-gante-capitulo-5-tablero-europa/3266262/?media=tve"></p:emision><p:emision titulo="Carlos de Gante - Capítulo 4: &quot;Príncipe y caballero&quot;" fecha="2015-09-23" tiempo="00:7:21" URL="http://www.rtve.es/m/alacarta/audios/carlos-de-gante/carlos-gante-capitulo-4-principe-caballero/3266320/?media=tve"></p:emision><p:emision titulo="Carlos de Gante - Capítulo 3: &quot;Matar al padre&quot;" fecha="2015-09-16" tiempo="00:5:56" URL="http://www.rtve.es/m/alacarta/audios/carlos-de-gante/carlos-gante-capitulo-3-matar-padre-chievres/3266318/?media=tve"></p:emision><p:emision titulo="Carlos de Gante - Capítulo 2: &quot;Mujeres en el poder&quot;" fecha="2015-09-09" tiempo="00:6:41" URL="http://www.rtve.es/m/alacarta/audios/carlos-de-gante/carlos-cap-2-2015-08-27t10-57-434301339/3266319/?media=tve"></p:emision><p:emision titulo="Carlos de Gante - Capítulo 1: &quot;Hijo de rey&quot;" fecha="2015-09-02" tiempo="00:7:29" URL="http://www.rtve.es/m/alacarta/audios/carlos-de-gante/carlos-gante-capitulo-1-hijo-rey/3266263/?media=tve"></p:emision></p:programa>

=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/amar-en-tiempos-revueltos.xml
<?xml version="1.0" ?>
<p:programa xmlns:p="http://www.example.org/ejercicio1-2"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/ejercicio1-2 Ejercicio1-2.xsd "
	id="amar-en-tiempos-revueltos">
	<p:nombre>Amar en tiempos revueltos</p:nombre>
	<p:URLprograma>http://www.rtve.es/m/alacarta/videos/amar-en-tiempos-revueltos/?media=tve</p:URLprograma>
	<p:URLimagen>http://img.rtve.es/imagenes/amar-tiempos-revueltos/1488798760813.png</p:URLimagen>
	<p:emision titulo="T7 - Capítulo 256 - Final 2ª Parte" fecha="2012-11-16"
		tiempo="00:56:12"
		URL="http://www.rtve.es/m/alacarta/videos/amar-en-tiempos-revueltos/amar-tiempos-revueltos-t7-capitulo-256-final-2-parte/1580482/?media=tve"></p:emision>
	<p:emision titulo="T7 - Capítulo 255 - Final 1ª parte" fecha="2012-11-16"
		tiempo="00:54:55"
		URL="http://www.rtve.es/m/alacarta/videos/amar-en-tiempos-revueltos/amar-tiempos-revueltos-t7-capitulo-255-final-1-parte/1580102/?media=tve"></p:emision>
	<p:emision titulo="T7 - Capítulo 254" fecha="2012-11-15"
		tiempo="00:54:42"
		URL="http://www.rtve.es/m/alacarta/videos/amar-en-tiempos-revueltos/amar-tiempos-revueltos-t7-capitulo-254/1580324/?media=tve"></p:emision>
	<p:emision titulo="T7 - Capítulo 253" fecha="2012-11-13"
		tiempo="00:55:10"
		URL="http://www.rtve.es/m/alacarta/videos/amar-en-tiempos-revueltos/amar-tiempos-revueltos-t7-capitulo-253/1578684/?media=tve"></p:emision>
	<p:emision titulo="T7 - Capítulo 252" fecha="2012-11-12"
		tiempo="00:54:03"
		URL="http://www.rtve.es/m/alacarta/videos/amar-en-tiempos-revueltos/amar-tiempos-revueltos-t7-capitulo-252/1577813/?media=tve"></p:emision>
	<p:emision titulo="T7 - Capítulo 251" fecha="2012-11-09"
		tiempo="00:54:26"
		URL="http://www.rtve.es/m/alacarta/videos/amar-en-tiempos-revueltos/amar-tiempos-revueltos-t7-capitulo-251/1574546/?media=tve"></p:emision>
	<p:emision titulo="T7 - Capítulo 250" fecha="2012-11-08"
		tiempo="00:54:44"
		URL="http://www.rtve.es/m/alacarta/videos/amar-en-tiempos-revueltos/amar-tiempos-revueltos-t7-capitulo-250/1574547/?media=tve"></p:emision>
	<p:emision titulo="T7 - Capítulo 249" fecha="2012-11-07"
		tiempo="00:54:50"
		URL="http://www.rtve.es/m/alacarta/videos/amar-en-tiempos-revueltos/amar-tiempos-revueltos-t7-capitulo-249/1573352/?media=tve"></p:emision>
</p:programa>
