=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/Ejercicio1-2.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/ejercicio1-2" xmlns="http://www.example.org/ejercicio1-2"
	elementFormDefault="qualified">

	<xs:complexType name="tipo_emision">
		<xs:attribute name="titulo" type="xs:string" />
		<xs:attribute name="fecha" type="xs:date" />
		<xs:attribute name="tiempo" type="xs:time" />
		<xs:attribute name="URL" type="xs:string" />
	</xs:complexType>

	<xs:element name="programa">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nombre" type="xs:string" />
				<xs:element name="URLprograma" type="xs:string" />
				<xs:element name="URLimagen" type="xs:string" />
				<xs:element name="emision" type="tipo_emision" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/balas-de-plata.xml
<?xml version="1.0" ?><p:programa xmlns:p="http://www.example.org/ejercicio1-2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ejercicio1-2 Ejercicio1-2.xsd " id="balas-de-plata"><p:nombre>Balas de plata</p:nombre><p:URLprograma>http://www.rtve.es/m/alacarta/videos/balas-de-plata/?media=tve</p:URLprograma><p:URLimagen>http://img.rtve.es/imagenes/balas-plata/1344519535411.jpg</p:URLimagen><p:emision titulo="Balas de plata - 18/07/08" fecha="2008-07-18" tiempo="00:1:06" URL="http://www.rtve.es/m/alacarta/videos/balas-de-plata/balas-plata-18-07-08/218205/?media=tve"></p:emision><p:emision titulo="Balas de plata - 10/07/08" fecha="2008-07-10" tiempo="00:1:09" URL="http://www.rtve.es/m/alacarta/videos/balas-de-plata/balas-plata-10-07-08/211512/?media=tve"></p:emision><p:emision titulo="Balas de plata - 03/07/08" fecha="2008-07-03" tiempo="00:54:56" URL="http://www.rtve.es/m/alacarta/videos/balas-de-plata/balas-plata-03-07-08/207072/?media=tve"></p:emision><p:emision titulo="Balas de plata - 27/06/08" fecha="2008-06-27" tiempo="00:1:02" URL="http://www.rtve.es/m/alacarta/videos/balas-de-plata/balas-plata-27-06-08/191392/?media=tve"></p:emision><p:emision titulo="Balas de plata - 19/06/08" fecha="2008-06-19" tiempo="00:59:56" URL="http://www.rtve.es/m/alacarta/videos/balas-de-plata/balas-plata-19-06-08/170452/?media=tve"></p:emision><p:emision titulo="Balas de plata - 12/06/08" fecha="2008-06-12" tiempo="00:1:09" URL="http://www.rtve.es/m/alacarta/videos/balas-de-plata/balas-plata-12-06-08/148392/?media=tve"></p:emision><p:emision titulo="Balas de plata - 05/06/08" fecha="2008-06-05" tiempo="00:1:01" URL="http://www.rtve.es/m/alacarta/videos/balas-de-plata/balas-plata-05-06-08/127792/?media=tve"></p:emision><p:emision titulo="Balas de plata - 30/05/08" fecha="2008-05-30" tiempo="00:1:05" URL="http://www.rtve.es/m/alacarta/videos/balas-de-plata/balas-plata-30-05-08/110732/?media=tve"></p:emision></p:programa>

=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/aqui-la-tierra.xml
<?xml version="1.0" ?><p:programa xmlns:p="http://www.example.org/ejercicio1-2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ejercicio1-2 Ejercicio1-2.xsd " id="aqui-la-tierra"><p:nombre>Aquí la Tierra</p:nombre><p:URLprograma>http://www.rtve.es/m/alacarta/videos/aqui-la-tierra/?media=tve</p:URLprograma><p:URLimagen>http://img.rtve.es/imagenes/aqui-tierra/1412768845520.png</p:URLimagen><p:emision titulo="Aquí la Tierra - 29/03/17        " fecha="2017-03-29" tiempo="00:28:36" URL="http://www.rtve.es/m/alacarta/videos/aqui-la-tierra/aqui-tierra-29-03-17/3961573/?media=tve"></p:emision><p:emision titulo="Aquí la Tierra - 28/03/17      " fecha="2017-03-28" tiempo="00:28:31" URL="http://www.rtve.es/m/alacarta/videos/aqui-la-tierra/aqui-tierra-28-03-17/3960210/?media=tve"></p:emision><p:emision titulo="Aquí la Tierra - 27/03/17        " fecha="2017-03-27" tiempo="00:29:43" URL="http://www.rtve.es/m/alacarta/videos/aqui-la-tierra/aqui-tierra-27-03-17/3959084/?media=tve"></p:emision><p:emision titulo="Aquí la Tierra - 26/03/17" fecha="2017-03-26" tiempo="00:31:30" URL="http://www.rtve.es/m/alacarta/videos/aqui-la-tierra/aqui-tierra-26-03-17/3957624/?media=tve"></p:emision><p:emision titulo="Aquí la tierra - 23/03/17" fecha="2017-03-23" tiempo="00:29:18" URL="http://www.rtve.es/m/alacarta/videos/aqui-la-tierra/aqui-tierra-23-03-17/3955012/?media=tve"></p:emision><p:emision titulo="Aquí la tierra - 22/03/17" fecha="2017-03-22" tiempo="00:29:21" URL="http://www.rtve.es/m/alacarta/videos/aqui-la-tierra/aqui-tierra-22-03-17/3953847/?media=tve"></p:emision><p:emision titulo="Aquí la tierra - 21/03/17" fecha="2017-03-21" tiempo="00:30:06" URL="http://www.rtve.es/m/alacarta/videos/aqui-la-tierra/aqui-tierra-21-03-17/3952123/?media=tve"></p:emision><p:emision titulo="Aquí la Tierra - 20/03/17" fecha="2017-03-20" tiempo="00:29:40" URL="http://www.rtve.es/m/alacarta/videos/aqui-la-tierra/aqui-tierra-20-03-17/3950335/?media=tve"></p:emision></p:programa>

=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/campanadas-de-fin-de-ano.xml
<?xml version="1.0" ?><p:programa xmlns:p="http://www.example.org/ejercicio1-2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ejercicio1-2 Ejercicio1-2.xsd " id="campanadas-de-fin-de-ano"><p:nombre>Campanadas de Fin de Año</p:nombre><p:URLprograma>http://www.rtve.es/m/alacarta/videos/campanadas-de-fin-de-ano/?media=tve</p:URLprograma><p:URLimagen>http://img.rtve.es/imagenes/campanadas-fin-ano/1351176107473.jpg</p:URLimagen><p:emision titulo="Campanadas 2016 en Canarias" fecha="2017-01-01" tiempo="00:14:59" URL="http://www.rtve.es/m/alacarta/videos/campanadas-de-fin-de-ano/campanadas-2016-canarias/3851479/?media=tve"></p:emision><p:emision titulo="Campanadas 2016" fecha="2016-12-31" tiempo="00:19:58" URL="http://www.rtve.es/m/alacarta/videos/campanadas-de-fin-de-ano/campanadas-2016/3851484/?media=tve"></p:emision><p:emision titulo="Campanadas Fin de año 2015 Canarias" fecha="2016-01-01" tiempo="00:7:45" URL="http://www.rtve.es/m/alacarta/videos/campanadas-de-fin-de-ano/campanadas-fin-ano-2015-canarias/3430621/?media=tve"></p:emision><p:emision titulo="Campanadas de Fin de Año 2015" fecha="2016-01-01" tiempo="00:5:28" URL="http://www.rtve.es/m/alacarta/videos/campanadas-de-fin-de-ano/campanadas-fin-ano-2016/3430458/?media=tve"></p:emision><p:emision titulo="Campanadas 2015" fecha="2015-12-31" tiempo="00:23:24" URL="http://www.rtve.es/m/alacarta/videos/campanadas-de-fin-de-ano/campanadas-2015/3430768/?media=tve"></p:emision><p:emision titulo="Campanadas Fin de año 2014 Canarias" fecha="2015-01-01" tiempo="00:9:36" URL="http://www.rtve.es/m/alacarta/videos/campanadas-de-fin-de-ano/campanadas-fin-ano-2014-canarias/2936476/?media=tve"></p:emision><p:emision titulo="Campanadas 2015" fecha="2014-12-31" tiempo="00:22:38" URL="http://www.rtve.es/m/alacarta/videos/campanadas-de-fin-de-ano/campanadas-2014/2936494/?media=tve"></p:emision><p:emision titulo="Campanadas de Fin de Año 2013" fecha="2013-12-31" tiempo="00:16:36" URL="http://www.rtve.es/m/alacarta/videos/campanadas-de-fin-de-ano/campanadas-entrada-2014-anne-igartiburu-pepe-rodriguez-jordi-cruz-desde-puerta-del-sol/2276053/?media=tve"></p:emision></p:programa>

=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/audiencia-abierta.xml
<?xml version="1.0" ?><p:programa xmlns:p="http://www.example.org/ejercicio1-2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ejercicio1-2 Ejercicio1-2.xsd " id="audiencia-abierta"><p:nombre>Audiencia abierta</p:nombre><p:URLprograma>http://www.rtve.es/m/alacarta/videos/audiencia-abierta/?media=tve</p:URLprograma><p:URLimagen>http://img.rtve.es/imagenes/audiencia-abierta/1349952396013.jpg</p:URLimagen><p:emision titulo="Audiencia Abierta - 25/03/17  " fecha="2017-03-25" tiempo="00:30:50" URL="http://www.rtve.es/m/alacarta/videos/audiencia-abierta/audiencia-abierta-25-03-17/3956620/?media=tve"></p:emision><p:emision titulo="Audiencia Abierta - 18/03/17     " fecha="2017-03-18" tiempo="00:30:32" URL="http://www.rtve.es/m/alacarta/videos/audiencia-abierta/audiencia-abierta-18-03-17/3948316/?media=tve"></p:emision><p:emision titulo="Audiencia Abierta - 11/03/17      " fecha="2017-03-11" tiempo="00:30:57" URL="http://www.rtve.es/m/alacarta/videos/audiencia-abierta/audiencia-abierta-11-03-17/3940983/?media=tve"></p:emision><p:emision titulo="Audiencia Abierta - 04/03/17            " fecha="2017-03-04" tiempo="00:30:46" URL="http://www.rtve.es/m/alacarta/videos/audiencia-abierta/audiencia-abierta-04-03-17/3933606/?media=tve"></p:emision><p:emision titulo="Audiencia Abierta - 25/02/17  " fecha="2017-02-25" tiempo="00:30:46" URL="http://www.rtve.es/m/alacarta/videos/audiencia-abierta/audiencia-abierta-25-02-17/3925861/?media=tve"></p:emision><p:emision titulo="Audiencia Abierta - 18/02/17" fecha="2017-02-18" tiempo="00:34:36" URL="http://www.rtve.es/m/alacarta/videos/audiencia-abierta/audiencia-abierta-18-02-17/3918930/?media=tve"></p:emision><p:emision titulo="Audiencia Abierta - 11/02/17" fecha="2017-02-11" tiempo="00:29:47" URL="http://www.rtve.es/m/alacarta/videos/audiencia-abierta/audiencia-abierta-11-02-17/3910959/?media=tve"></p:emision><p:emision titulo="Audiencia Abierta - 04/02/17 " fecha="2017-02-04" tiempo="00:30:32" URL="http://www.rtve.es/m/alacarta/videos/audiencia-abierta/audiencia-abierta-04-02-17/3899920/?media=tve"></p:emision></p:programa>

=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/carlos-rey-emperador.xml
<?xml version="1.0" ?><p:programa xmlns:p="http://www.example.org/ejercicio1-2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ejercicio1-2 Ejercicio1-2.xsd " id="carlos-rey-emperador"><p:nombre>Carlos, Rey Emperador</p:nombre><p:URLprograma>http://www.rtve.es/m/alacarta/videos/carlos-rey-emperador/?media=tve</p:URLprograma><p:URLimagen>http://img.rtve.es/imagenes/carlos-rey-emperador/1488798893664.png</p:URLimagen><p:emision titulo="Capítulo 17" fecha="2016-01-25" tiempo="00:1:14" URL="http://www.rtve.es/m/alacarta/videos/carlos-rey-emperador/carlos-rey-cap17-220116/3455326/?media=tve"></p:emision><p:emision titulo="Capítulo 16" fecha="2016-01-25" tiempo="00:1:17" URL="http://www.rtve.es/m/alacarta/videos/carlos-rey-emperador/carlos-rey-cap16/3455288/?media=tve"></p:emision><p:emision titulo="Capítulo 15" fecha="2016-01-18" tiempo="00:1:15" URL="http://www.rtve.es/m/alacarta/videos/carlos-rey-emperador/carlos-cap15-120116/3441799/?media=tve"></p:emision><p:emision titulo="Capítulo 14" fecha="2016-01-11" tiempo="00:1:17" URL="http://www.rtve.es/m/alacarta/videos/carlos-rey-emperador/carlos-rey-emperador-cap14/3438518/?media=tve"></p:emision><p:emision titulo="Capítulo 13" fecha="2015-11-23" tiempo="00:1:17" URL="http://www.rtve.es/m/alacarta/videos/carlos-rey-emperador/carlos-cap13-201115/3372984/?media=tve"></p:emision><p:emision titulo="Capítulo 12" fecha="2015-11-23" tiempo="00:1:18" URL="http://www.rtve.es/m/alacarta/videos/carlos-rey-emperador/carlos-rey-emperador-capitulo-12/3372465/?media=tve"></p:emision><p:emision titulo="Capítulo 11" fecha="2015-11-16" tiempo="00:1:15" URL="http://www.rtve.es/m/alacarta/videos/carlos-rey-emperador/carlos-cap11/3361661/?media=tve"></p:emision><p:emision titulo="Capítulo 10" fecha="2015-11-09" tiempo="00:1:15" URL="http://www.rtve.es/m/alacarta/videos/carlos-rey-emperador/carlos-rey-cap-10-051015/3348777/?media=tve"></p:emision></p:programa>

=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/acacias-38.xml
<?xml version="1.0" ?>
<p:programa xmlns:p="http://www.example.org/ejercicio1-2"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/ejercicio1-2 Ejercicio1-2.xsd "
	id="acacias-38">
	<p:nombre>Acacias 38</p:nombre>
	<p:URLprograma>http://www.rtve.es/m/alacarta/videos/acacias-38/?media=tve</p:URLprograma>
	<p:URLimagen>http://img.rtve.es/imagenes/acacias-38/1425305370705.png</p:URLimagen>
	<p:emision titulo="Capítulo 510  " fecha="2017-05-08" tiempo="00:52:30"
		URL="http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-510/4011500/?media=tve"></p:emision>
	<p:emision titulo="Capítulo 509" fecha="2017-05-05" tiempo="00:52:13"
		URL="http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-509/4008271/?media=tve"></p:emision>
	<p:emision titulo="Capítulo 508" fecha="2017-05-04" tiempo="00:52:13"
		URL="http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-508/4006809/?media=tve"></p:emision>
	<p:emision titulo="Capítulo 507" fecha="2017-05-03" tiempo="00:52:47"
		URL="http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-507/4005277/?media=tve"></p:emision>
	<p:emision titulo="Capítulo 506" fecha="2017-05-02" tiempo="00:52:24"
		URL="http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-506/4003639/?media=tve"></p:emision>
	<p:emision titulo="Capítulo 505" fecha="2017-04-28" tiempo="00:52:21"
		URL="http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-505/3999036/?media=tve"></p:emision>
	<p:emision titulo="Capítulo 504" fecha="2017-04-27" tiempo="00:52:14"
		URL="http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-504/3997245/?media=tve"></p:emision>
	<p:emision titulo="Capítulo 503" fecha="2017-04-26" tiempo="00:53:40"
		URL="http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-503/3995452/?media=tve"></p:emision>
</p:programa>

=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/canarias-mediodia.xml
<?xml version="1.0" ?><p:programa xmlns:p="http://www.example.org/ejercicio1-2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ejercicio1-2 Ejercicio1-2.xsd " id="canarias-mediodia"><p:nombre>Canarias Mediodía</p:nombre><p:URLprograma>http://www.rtve.es/m/alacarta/videos/canarias-mediodia/?media=tve</p:URLprograma><p:URLimagen>http://img.rtve.es/imagenes/canarias-mediodia/1317031403724.jpg</p:URLimagen><p:emision titulo="Canarias Mediodía - 27/07/12" fecha="2012-07-27" tiempo="00:18:19" URL="http://www.rtve.es/m/alacarta/videos/canarias-mediodia/canarias-mediodia-27-07-12/1492416/?media=tve"></p:emision><p:emision titulo="Canarias Mediodía - 26/07/2012" fecha="2012-07-26" tiempo="00:20:13" URL="http://www.rtve.es/m/alacarta/videos/canarias-mediodia/canarias-mediodia-26-07-2012/1491538/?media=tve"></p:emision><p:emision titulo="Canarias Mediodía 25/07/2012" fecha="2012-07-25" tiempo="00:20:39" URL="http://www.rtve.es/m/alacarta/videos/canarias-mediodia/canarias-mediodia-25-07-2012/1490635/?media=tve"></p:emision><p:emision titulo="Canarias Mediodía - 24/07/2012" fecha="2012-07-24" tiempo="00:20:24" URL="http://www.rtve.es/m/alacarta/videos/canarias-mediodia/canarias-mediodia-24-07-2012/1489806/?media=tve"></p:emision><p:emision titulo="Canarias Mediodía - 23/07/2012" fecha="2012-07-23" tiempo="00:19:46" URL="http://www.rtve.es/m/alacarta/videos/canarias-mediodia/canarias-mediodia-23-07-2012/1489425/?media=tve"></p:emision><p:emision titulo="Canarias mediodia - 20/07/12" fecha="2012-07-20" tiempo="00:20:39" URL="http://www.rtve.es/m/alacarta/videos/canarias-mediodia/canarias-mediodia-20-07-12/1485750/?media=tve"></p:emision><p:emision titulo="Canarias Mediodía -19/07/2012" fecha="2012-07-19" tiempo="00:20:43" URL="http://www.rtve.es/m/alacarta/videos/canarias-mediodia/canarias-mediodia-19-07-2012/1470265/?media=tve"></p:emision><p:emision titulo="Canarias Mediodía - 18/07/2012" fecha="2012-07-18" tiempo="00:22:38" URL="http://www.rtve.es/m/alacarta/videos/canarias-mediodia/canarias-mediodia-18-07-2012/1468503/?media=tve"></p:emision></p:programa>

=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/al-filo-de-la-ley.xml
<?xml version="1.0" ?>
<p:programa xmlns:p="http://www.example.org/ejercicio1-2"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/ejercicio1-2 Ejercicio1-2.xsd "
	id="al-filo-de-la-ley">
	<p:nombre>Al filo de la ley </p:nombre>
	<p:URLprograma>http://www.rtve.es/m/alacarta/videos/al-filo-de-la-ley/?media=tve</p:URLprograma>
	<p:URLimagen>http://img.rtve.es/imagenes/filo-ley/1342163122146.jpg</p:URLimagen>
	<p:emision titulo="Fantasmas del pasado" fecha="2012-09-15"
		tiempo="00:1:04"
		URL="http://www.rtve.es/m/alacarta/videos/al-filo-de-la-ley/filo-ley-fantasmas-del-pasado/1528105/?media=tve"></p:emision>
	<p:emision titulo="Un gran equipo" fecha="2012-09-08" tiempo="00:1:03"
		URL="http://www.rtve.es/m/alacarta/videos/al-filo-de-la-ley/filo-ley/1523206/?media=tve"></p:emision>
	<p:emision titulo="Una mujer pública" fecha="2012-09-08"
		tiempo="00:1:00"
		URL="http://www.rtve.es/m/alacarta/videos/al-filo-de-la-ley/filo-ley-mujer-publica/1523202/?media=tve"></p:emision>
	<p:emision titulo="Adiós a la inocencia" fecha="2012-09-01"
		tiempo="00:59:59"
		URL="http://www.rtve.es/m/alacarta/videos/al-filo-de-la-ley/filo-ley-adios-inocencia/1517943/?media=tve"></p:emision>
	<p:emision titulo="El sexo de los abogados" fecha="2012-08-25"
		tiempo="00:1:04"
		URL="http://www.rtve.es/m/alacarta/videos/al-filo-de-la-ley/filo-ley-sexo-abogados/1513363/?media=tve"></p:emision>
	<p:emision titulo="Secuestro" fecha="2012-08-17" tiempo="00:1:00"
		URL="http://www.rtve.es/m/alacarta/videos/al-filo-de-la-ley/filo-ley-secuestro/1508499/?media=tve"></p:emision>
	<p:emision titulo="Esos juegos" fecha="2012-08-11" tiempo="00:1:01"
		URL="http://www.rtve.es/m/alacarta/videos/al-filo-de-la-ley/filo-ley-esos-juegos/1504382/?media=tve"></p:emision>
	<p:emision titulo="Hermanos de sangre" fecha="2012-08-04"
		tiempo="00:1:02"
		URL="http://www.rtve.es/m/alacarta/videos/al-filo-de-la-ley/filo-ley-hermanos-sangre/1498608/?media=tve"></p:emision>
</p:programa>
