=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/Ejercicio1-2.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/ejercicio1-2" xmlns="http://www.example.org/ejercicio1-2"
	elementFormDefault="qualified">

	<xs:complexType name="tipo_emision">
		<xs:attribute name="titulo" type="xs:string" />
		<xs:attribute name="fecha" type="xs:date" />
		<xs:attribute name="tiempo" type="xs:time" />
		<xs:attribute name="URL" type="xs:string" />
	</xs:complexType>

	<xs:element name="programa">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nombre" type="xs:string" />
				<xs:element name="URLprograma" type="xs:string" />
				<xs:element name="URLimagen" type="xs:string" />
				<xs:element name="emision" type="tipo_emision" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/capitan-q.xml
<?xml version="1.0" ?><p:programa xmlns:p="http://www.example.org/ejercicio1-2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ejercicio1-2 Ejercicio1-2.xsd " id="capitan-q"><p:nombre>Capitán Q</p:nombre><p:URLprograma>http://www.rtve.es/m/alacarta/videos/capitan-q/?media=tve</p:URLprograma><p:URLimagen>http://img.rtve.es/imagenes/capitan/1432547648387.png</p:URLimagen><p:emision titulo="Un final de viaje con sabor vasco" fecha="2016-09-08" tiempo="00:1:02" URL="http://www.rtve.es/m/alacarta/videos/capitan-q/capitan-final-viaje-sabor-vasco/3713673/?media=tve"></p:emision><p:emision titulo="Costa asturiana" fecha="2016-09-07" tiempo="00:57:24" URL="http://www.rtve.es/m/alacarta/videos/capitan-q/capitan-costa-asturiana/3712581/?media=tve"></p:emision><p:emision titulo="Galicia y la temida 'Costa da Morte'" fecha="2016-09-06" tiempo="00:57:03" URL="http://www.rtve.es/m/alacarta/videos/capitan-q/capitan-galicia-temida-costa-da-morte/3711592/?media=tve"></p:emision><p:emision titulo="De aventura en las costas de Cádiz" fecha="2016-09-05" tiempo="00:55:36" URL="http://www.rtve.es/m/alacarta/videos/capitan-q/capitan-aventura-costas-cadiz/3710754/?media=tve"></p:emision><p:emision titulo="El Estrecho de Gibraltar" fecha="2016-09-02" tiempo="00:50:44" URL="http://www.rtve.es/m/alacarta/videos/capitan-q/capitan-estrecho-gibraltar/3708946/?media=tve"></p:emision><p:emision titulo="Jávea - Isleta del Moro" fecha="2016-09-01" tiempo="00:53:35" URL="http://www.rtve.es/m/alacarta/videos/capitan-q/capitan-javea-isleta-del-moro/3707986/?media=tve"></p:emision><p:emision titulo="Sant Carles de la Râpita-Ibiza" fecha="2016-08-31" tiempo="00:53:07" URL="http://www.rtve.es/m/alacarta/videos/capitan-q/capitan-sant-carles-rapita-ibiza/3707209/?media=tve"></p:emision><p:emision titulo="Cadaqués - L'Ametlla de Mar" fecha="2016-08-30" tiempo="00:53:11" URL="http://www.rtve.es/m/alacarta/videos/capitan-q/capitan-cadaques-lametlla-mar/3706299/?media=tve"></p:emision></p:programa>

=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml-bd/buscamundos.xml
<?xml version="1.0" ?><p:programa xmlns:p="http://www.example.org/ejercicio1-2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ejercicio1-2 Ejercicio1-2.xsd " id="buscamundos"><p:nombre>Buscamundos</p:nombre><p:URLprograma>http://www.rtve.es/m/alacarta/videos/buscamundos/?media=tve</p:URLprograma><p:URLimagen>http://img.rtve.es/imagenes/buscamundos/1294827239577.png</p:URLimagen><p:emision titulo="Egipto" fecha="2013-01-09" tiempo="00:58:11" URL="http://www.rtve.es/m/alacarta/videos/buscamundos/buscamundos-egipto/1648422/?media=tve"></p:emision><p:emision titulo="Turquía: la frontera de Asia" fecha="2012-12-19" tiempo="00:55:22" URL="http://www.rtve.es/m/alacarta/videos/buscamundos/buscamundos-turquia-frontera-asia/1618342/?media=tve"></p:emision><p:emision titulo="Vietnam" fecha="2012-12-12" tiempo="00:57:51" URL="http://www.rtve.es/m/alacarta/videos/buscamundos/buscamundos-vietnam/1609223/?media=tve"></p:emision><p:emision titulo="Las Vegas, ciudad de mentira" fecha="2012-12-05" tiempo="00:59:39" URL="http://www.rtve.es/m/alacarta/videos/buscamundos/buscamundos-vegas-ciudad-mentira/1536154/?media=tve"></p:emision><p:emision titulo="Tanzania" fecha="2012-11-28" tiempo="00:57:55" URL="http://www.rtve.es/m/alacarta/videos/buscamundos/buscamundos-20121127-0025-169/1593054/?media=tve"></p:emision><p:emision titulo="Europa en crisis" fecha="2012-11-21" tiempo="00:57:36" URL="http://www.rtve.es/m/alacarta/videos/buscamundos/buscamundos-europa-crisis/1585322/?media=tve"></p:emision><p:emision titulo="Guatemala, tierra de volcanes " fecha="2012-11-14" tiempo="00:57:07" URL="http://www.rtve.es/m/alacarta/videos/buscamundos/buscamundos-guatemala-tierra-volcanes-leyendas/1284847/?media=tve"></p:emision><p:emision titulo="Los mares del fín del mundo" fecha="2012-11-07" tiempo="00:55:10" URL="http://www.rtve.es/m/alacarta/videos/buscamundos/buscamundos-mares-del-fin-del-mundoturismo-funerario/1572423/?media=tve"></p:emision></p:programa>
