=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml/Ejercicio1-2.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/ejercicio1-2" xmlns="http://www.example.org/ejercicio1-2"
	elementFormDefault="qualified">

	<xs:complexType name="tipo_emision">
		<xs:attribute name="titulo" type="xs:string" />
		<xs:attribute name="fecha" type="xs:date" />
		<xs:attribute name="tiempo" type="xs:time" />
		<xs:attribute name="URL" type="xs:string" />
	</xs:complexType>
	
	<xs:complexType name="tipo_producto">
		<xs:attribute name="ASIN" type="xs:string" />
		<xs:attribute name="Titulo" type="xs:string" />
		<xs:attribute name="urlImgSmall" type="xs:string" />
		<xs:attribute name="urlImgLarge" type="xs:string" />
		<xs:attribute name="Precio" type="xs:double" />
		<xs:attribute name="URL" type="xs:string" />
	</xs:complexType>

	<xs:element name="programa">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nombre" type="xs:string" />
				<xs:element name="URLprograma" type="xs:string" />
				<xs:element name="URLimagen" type="xs:string" />
				<xs:element name="emision" type="tipo_emision"  maxOccurs="unbounded" />
				<xs:element name="producto" type="tipo_producto" minOccurs="0" maxOccurs="3"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JRamonMC/arsoft/arsoft-jrmcm-ah/xml/acacias-38-procesado.xml
<?xml version="1.0" ?>
<p:programa xmlns:p="http://www.example.org/ejercicio1-2"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/ejercicio1-2 Ejercicio1-2.xsd "
	id="acacias-38">
	<p:nombre>Acacias 38</p:nombre>
	<p:URLprograma>http://www.rtve.es/m/alacarta/videos/acacias-38/?media=tve</p:URLprograma>
	<p:URLimagen>http://img.rtve.es/imagenes/acacias-38/1425305370705.png</p:URLimagen>
	<p:emision titulo="Capítulo 483" fecha="2017-03-27" tiempo="00:54:00"
		URL="http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-483/3958967/?media=tve"></p:emision>
	<p:emision titulo="Capítulo 482" fecha="2017-03-24" tiempo="00:54:01"
		URL="http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-482/3956141/?media=tve"></p:emision>
	<p:emision titulo="Capítulo 481" fecha="2017-03-23" tiempo="00:54:05"
		URL="http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-cap-481-hd/3954902/?media=tve"></p:emision>
	<p:emision titulo="Capítulo 480" fecha="2017-03-22" tiempo="00:54:05"
		URL="http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-480/3953756/?media=tve"></p:emision>
	<p:emision titulo="Capítulo 479" fecha="2017-03-21" tiempo="00:54:25"
		URL="http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-479/3951980/?media=tve"></p:emision>
	<p:emision titulo="Capítulo 478" fecha="2017-03-20" tiempo="00:54:24"
		URL="http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-478/3950259/?media=tve"></p:emision>
	<p:emision titulo="Capítulo 477" fecha="2017-03-17" tiempo="00:54:05"
		URL="http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-477/3947771/?media=tve"></p:emision>
	<p:emision titulo="Capítulo 476" fecha="2017-03-16" tiempo="00:55:38"
		URL="http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-476/3946317/?media=tve"></p:emision>
</p:programa>
